openapi: 3.0.0
info:
  title: API Documentation
  description: Student workflow organizer API Documentation with swagger.
  version: 1.0
  contact:
    email: contact@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  servers:
    url: http://localhost:4000
    description: THis is my local Server
